### ISSUE TITLE
Bug garage

### ISSUE THREAD

**Issue by jereparemonpc** [Sighmir/vrp_garages#1]
Hi, Your garage is great, but you can not sell it and you can not close the vehicle with the "vehicule" menu.

**Comment by Sighmir** [comment]
I have used the vehicle menu and it seems to be working fine for me, after the event is added, do you get any console errors? 
This garage was not intended to sell vehicles it's there to give you the ability to take out the vehicle with the saved customization from vrp_lscutoms, to sell the vehicles you still have to use the default vrp garages for each model.

**Comment by jereparemonpc** [comment]
No I have no mistake. After buying the vehicle from Simeon. I try to open the vehicle menu, is it puts me a message: "No vehicle belonging to you near.

**Comment by Sighmir** [comment]
Have you added the event under the variable vehicles on client basic_garages.lua ?

**Comment by jereparemonpc** [comment]
Yes at the top of the page

**Comment by UtraTM** [comment]
seems like when i look into the code we need ply garages or?

**Comment by Sighmir** [comment]
This is a port from ply_garages. The code is working fine for a few people, you have to put the event under the vehicles variable, on the top of /client/basic_vehicles.lua, I have been using these same resources for almost 2 weeks with no problems.
