### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Eulogies** [Sighmir/vrp_garages#12]
No idea what triggered it, all I did was lockpick a car.

`Error running call reference function for resource vrp_nocarjack: citizen:/scripting/lua/scheduler.lua:348: server.lua:16: attempt to index a nil value (local 'identity')
stack traceback:
        server.lua:16: in upvalue 'ref'
        citizen:/scripting/lua/scheduler.lua:334: in function <citizen:/scripting/lua/scheduler.lua:333>
        [C]: in function 'xpcall'
        citizen:/scripting/lua/scheduler.lua:333: in function <citizen:/scripting/lua/scheduler.lua:332>
stack traceback:
        [C]: in function 'error'
        citizen:/scripting/lua/scheduler.lua:348: in function <citizen:/scripting/lua/scheduler.lua:319>
Error resuming coroutine: citizen:/scripting/lua/MessagePack.lua:830: missing bytes
stack traceback:
        [C]: in function 'error'
        citizen:/scripting/lua/MessagePack.lua:830: in method 'underflow'
        citizen:/scripting/lua/MessagePack.lua:465: in field 'any'
        citizen:/scripting/lua/MessagePack.lua:860: in field 'unpack'
        citizen:/scripting/lua/scheduler.lua:560: in upvalue 'callback'
        lib/utils.lua:43: in upvalue 'finish'
        lib/utils.lua:48: in function <lib/utils.lua:48>`

**Comment by Sighmir** [comment]
Error running call reference function for resource vrp_nocarjack: citizen:/scripting/lua/scheduler.lua:348: server.lua:16: attempt to index a nil value (local 'identity') stack traceback: server.lua:16:
According to this the error is related to vrp_nocarjack on line 16 but theres no identity on line 16 of the original version of https://github.com/Sighmir/vrp_nocarjack/blob/vRP/vrp_nocarjack/client.lua

**Comment by Sighmir** [comment]
Error running call reference function for resource vrp_nocarjack: citizen:/scripting/lua/scheduler.lua:348: server.lua:16: attempt to index a nil value (local 'identity') stack traceback: server.lua:16
The only reason you would get a nil value on that line is if the user_id is incalid, source is invalid, or the client doesnt have an identity on the database, or database conection was blocked by a different MySQL issue.
