### ISSUE TITLE
Can't sell vehicles in garage

### ISSUE THREAD

**Issue by Mallingdk** [Sighmir/vrp_garages#14]
why is it not possible to sell vehicles in the garage i can't see it in the menu

**Comment by paulpuscas89** [comment]
U can sell cars if you want but not in those with blue mark , but u can sel them at the original garages come from vrp . all u need to do is to add them to vrp/cf/garages from vrp_showroom and to have the same prices with witch you buy them from showroom.

**Comment by Sighmir** [comment]
@paulpuscas89 is correct. You have to sell cars at the original vRP garages.
The showroom doesn't have the "selling" functionality because it was never intended to replace the original vRP garages, it is supposed to work side-by-side with them.

**Comment by Mallingdk** [comment]
So i need to have both the vrp_garages whit the blue mark and the original vRP garages so selling.. the sell funktion is not in your vRP-garages?

**Comment by paulpuscas89** [comment]
yes u need to have both of them
