### ISSUE TITLE
Can´t store my vehicle?

### ISSUE THREAD

**Issue by SLoxxy21** [Sighmir/vrp_garages#15]
When i buy a car, and take it out, from the garage and try to park it. It says " no vehicle near" something like that :D

**Comment by paulpuscas89** [comment]
did u buy the car from showroom or vrp garages?

**Comment by SLoxxy21** [comment]
showroom

**Comment by Sighmir** [comment]
After buying a car at the showroom it should be added to the database with its owner, model and plate.
If you can, verify that the columns are created for vRP_lscustoms and vRP_showroom and look for any errors on console upon realizing the purchase.
