### ISSUE TITLE
No owned vehicle near.

### ISSUE THREAD

**Issue by chaixshot** [Sighmir/vrp_garages#16]
Get vehicle from garage but K menu (vrp/modules/basic_garage.lua - local function ch_vehicle(player,choice)) not working

**Comment by Sighmir** [comment]
Have you added the event for Vehicle button compatibility on client/basic_garage.lua ?

**Comment by chaixshot** [comment]
how? pls help.

**Comment by chaixshot** [comment]
oh i nver seen readme.md befor.

**Comment by Sighmir** [comment]
Follow the instructions on the readme and it should work.
