### ISSUE TITLE
Cant store car

### ISSUE THREAD

**Issue by UtraTM** [Sighmir/vrp_garages#2]
Hello,

i found your very nice addons for vRP here.

i isntalled the basic vrp stuff andd your garage, showroom and lscustoms.

I cant store my car in 1 of the 4 garages on the map.

DO i need to delete the orig garages or how is this handeld?

Thank you ver ymuch

**Comment by UtraTM** [comment]
Seems like it happens first time you buy the car. on re join you can take it out and it looks also like it saves the tuning then.

But there are still the old garages inside. So we should delete them from the cfg files or. The vehicle shops we dont need?

**Comment by UtraTM** [comment]
seems like when i look into the code we need ply garages or?

**Comment by Sighmir** [comment]
The garages work fine together, if you had to delete anything I'd say on the readme file, you just have to do what the readme tells you, leave the vRP garages in, take your vehicles out of the vrp_garages addon, use the default garages to sell and buy vehicles or simeon just to buy vehicles. You dont need any other script. This is a modification from ply_garages for vRP.
