### ISSUE TITLE
I added the code in the readme but still dont work

### ISSUE THREAD

**Issue by UtraTM** [Sighmir/vrp_garages#3]
Hello,
i added the code here:

local vehicles = {}

	AddEventHandler('vrp_garages:setVehicle', function(vtype, vehicle)
	vehicles[vtype] = vehicle
	end)

function tvRP.spawnGarageVehicle(vtype,name) -- vtype is the vehicle type (one vehicle per type allowed at the same time)

  local vehicle = vehicles[vtype]
  if vehicle and not IsVehicleDriveable(vehicle[3]) then -- precheck if vehicle is undriveable
    -- despawn vehicle
    SetVehicleHasBeenOwnedByPlayer(vehicle[3],false)
    Citizen.InvokeNative(0xAD738C3085FE7E11, vehicle[3], false, true) -- set not as mission entity
    SetVehicleAsNoLongerNeeded(Citizen.PointerValueIntInitialized(vehicle[3]))
    Citizen.InvokeNative(0xEA386986E786A54F, Citizen.PointerValueIntInitialized(vehicle[3]))
    vehicles[vtype] = nil
  end

but when i buy a vehicle in the vrp garages i can not get them from the new garages :(
When i look into the database it has no Plate set an nothing when buying from the original garage.
But i need some point to sell the vehicles thats why i used and all buy garage for it. But it seems to not work when buying an car there.

When using the original garages the tuning seems to be overwritten when taking out the car then :(
From the original garage its not saved.
And from the new ones it gets the correct car out when getting it. Wierd :D

**Comment by Sighmir** [comment]
"Add:
```
AddEventHandler('vrp_garages:setVehicle', function(vtype, vehicle)
	vehicles[vtype] = vehicle
end)
```
to the top of your vrp/client/basic_garage.lua, under the local vehicles variable, **for vehicle button compatibility.**"
That code doesnt make the vehicles you buy from basic_garages work with vrp_garages, it makes the ones you bought from showroom, the ones that work with the garages, work with the vehicle buttom.

You have to buy the vehicles on showroom, sell them on specific basic_garages, take them out at vrp_garages.
