### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by WingedHussarr** [Sighmir/vrp_garages#4]
I cannot store my car, it does recognise it as it doesnt display the message where it says no vehicles nearby. I also cannot retrieve any vehicles (none are in the list).

I think it may be linked with this issue: https://github.com/Sighmir/vrp_lscustoms/issues/2

**Comment by Sighmir** [comment]
The resource works fine. An issue named "Does not work" doesnt really tell me much, the cars have to be bought at the vrp_showroom, then you can modify then in the vrp_lscustoms and store them at vrp_garages.
