### ISSUE TITLE
Error when people join server

### ISSUE THREAD

**Issue by fdetty22** [Sighmir/vrp_garages#6]
![captur](https://user-images.githubusercontent.com/31628471/30034362-d82813a8-916e-11e7-8c08-623c69988b85.JPG)

**Comment by Sighmir** [comment]
Weird... Those always happen ? What about the second vrp callback error? Does that one happens if you remove vrp_garages of the server.cfg ? Did it cause anything to stop working like usual ?

I need as much informationa as I can to be able to help.
